compiler="cl /EHsc /std:c++17"

all: avl.exe hash1.exe

avl.exe: 
	$(compiler) avl.cpp
	
hash1.exe:
	$(compiler) hash1.cpp
	
hash2.exe:
	$(compiler) hash2.cpp
	
hashmap.exe:
	$(compiler) hashmap.cpp
	
	
Clean: 
	del *.obj 
	del *.exe